orbs:
  gcr: circleci/gcp-gcr@0.6.1

version: 2.1
jobs:
  pytest:
    docker:
      - image: python:3.6

    working_directory: ~/my-webapp

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            cd my-webapp
            pip3 install pytest
            pip3 install pytest-cov
            python3 -m pytest --cov --cov-report=html:reports --junitxml=test-reports/junit.xml

      - store_test_results:
          path: my-webapp/test-reports

      - store_artifacts:
          path: my-webapp/test-reports    

      - store_artifacts:
          path: my-webapp/reports
          destination: test-reports

  Build-Push-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - gcr/build-and-push-image:
          context: gcloud
          image: spike-circleci/my-webapp
          registry-url: gcr.io


workflows:
  version: 2
  test_and_build:
    jobs:
      - pytest
      - Build-Push-Docker:
          requires:
            - pytest

          
