version: 2
jobs:
  pytest:
    docker:
      - image: python:3.6

    working_directory: ~/my-webapp

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            cd my-webapp
            pip3 install pytest
            pip3 install pytest-cov
            python3 -m pytest --cov --cov-report=html:reports --junitxml=test-reports/junit.xml

      - store_test_results:
          path: my-webapp/test-reports

      - store_artifacts:
          path: my-webapp/test-reports    

      - store_artifacts:
          path: my-webapp/reports
          destination: test-reports

  # https://circleci.com/docs/2.0/google-auth/
  # https://circleci.com/docs/2.0/google-container-engine/
  # https://cloud.google.com/container-registry/docs/pushing
  build-docker:
    context: gcloud
    machine: true
    steps:
      - checkout

      - run:
          name: build docker image
          command: |
            echo ${GCLOUD_TEST}
            cat ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            cd my-webapp
            docker build --rm=false -t gcr.io/spike-circle/my-webapp:$CIRCLE_SHA1 .
            gcloud --quiet config set project spike-circleci
            gcloud docker -- push gcr.io/spike-circleci/my-webapp:$CIRCLE_SHA1          


workflows:
  version: 2
  test_and_build:
    jobs:
      - pytest
      - build-docker:
          requires:
            - pytest

          


